CREATE TABLE IF NOT EXISTS schema_migrations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  version VARCHAR(255) NOT NULL UNIQUE,
  filename VARCHAR(255) NOT NULL,
  applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  checksum VARCHAR(64) NULL COMMENT 'SHA256 of migration file'
);

INSERT IGNORE INTO schema_migrations (version, filename, applied_at) VALUES
  ('000_create_schema_migrations.sql', '000_create_schema_migrations.sql', NOW()),
  ('001_fix_customer_password_hash.sql', '001_fix_customer_password_hash.sql', NOW()),
  ('002_fix_import_trigger.sql', '002_fix_import_trigger.sql', NOW()),
  ('003_fix_dangerous_cascades.sql', '003_fix_dangerous_cascades.sql', NOW()),
  ('004_add_updated_at.sql', '004_add_updated_at.sql', NOW()),
  ('005_add_soft_delete.sql', '005_add_soft_delete.sql', NOW()),
  ('006_add_indexes.sql', '006_add_indexes.sql', NOW()),
  ('007_add_invoice_status.sql', '007_add_invoice_status.sql', NOW()),
  ('008_create_audit_logs.sql', '008_create_audit_logs.sql', NOW()),
  ('009_create_inventory_movements.sql', '009_create_inventory_movements.sql', NOW()),
  ('010_create_rbac_tables.sql', '010_create_rbac_tables.sql', NOW()),
  ('011_create_product_images.sql', '011_create_product_images.sql', NOW()),
  ('012_create_promotions.sql', '012_create_promotions.sql', NOW()),
  ('013_create_notifications.sql', '013_create_notifications.sql', NOW()),
  ('014_create_settings.sql', '014_create_settings.sql', NOW()),
  ('015_fix_returns_refund_logic.sql', '015_fix_returns_refund_logic.sql', NOW()),
  ('015_normalize_skin_types.sql', '015_normalize_skin_types.sql', NOW()),
  ('016_create_refresh_tokens.sql', '016_create_refresh_tokens.sql', NOW()),
  ('017_create_login_attempts.sql', '017_create_login_attempts.sql', NOW()),
  ('018_create_payment_transactions.sql', '018_create_payment_transactions.sql', NOW()),
  ('019_create_shipping_and_addresses.sql', '019_create_shipping_and_addresses.sql', NOW()),
  ('020_create_returns.sql', '020_create_returns.sql', NOW()),
  ('021_add_check_constraints.sql', '021_add_check_constraints.sql', NOW()),
  ('022_add_rbac_enhancements.sql', '022_add_rbac_enhancements.sql', NOW()),
  ('023_fix_leave_request_logic.sql', '023_fix_leave_request_logic.sql', NOW()),
  ('024_enforce_import_cost_source_of_truth.sql', '024_enforce_import_cost_source_of_truth.sql', NOW()),
  ('025_add_resignation_leave_type.sql', '025_add_resignation_leave_type.sql', NOW()),
  ('026_enforce_unique_active_user_employee.sql', '026_enforce_unique_active_user_employee.sql', NOW()),
  ('027_ensure_return_item_refund_subtotal.sql', '027_ensure_return_item_refund_subtotal.sql', NOW()),
  ('028_fix_gender_enum_encoding.sql', '028_fix_gender_enum_encoding.sql', NOW()),
  ('029_polish_demo_text_content.sql', '029_polish_demo_text_content.sql', NOW()),
  ('030_professionalize_demo_copy.sql', '030_professionalize_demo_copy.sql', NOW()),
  ('031_fix_invoice_crm_status_accounting.sql', '031_fix_invoice_crm_status_accounting.sql', NOW()),
  ('032_create_salary_bonus_adjustments.sql', '032_create_salary_bonus_adjustments.sql', NOW()),
  ('033_add_supplier_products_mapping.sql', '033_add_supplier_products_mapping.sql', NOW()),
  ('034_create_attendance_module.sql', '034_create_attendance_module.sql', NOW()),
  ('035_harden_internal_rbac_and_role_bootstrap.sql', '035_harden_internal_rbac_and_role_bootstrap.sql', NOW()),
  ('036_cleanup_rbac_roles.sql', '036_cleanup_rbac_roles.sql', NOW());
